import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/provider/queryProvider";
import AppBase from "@/provider/AppBase";
import { Suspense } from "react";

const Whois = localFont({
  variable: "--font-whois",
  src: "../public/Whois-mono-master/webfonts/whois-mono.woff",
});

export const metadata: Metadata = {
  title: "Krest biss application",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  maximumScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Whois.className}`}>
        <QueryProvider>
          <Suspense>
            <AppBase>{children}</AppBase>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
